### ISSUE TITLE
FaceID disables randomly

### ISSUE THREAD

**Issue by satindergrewal** [Meshbits/pirate-chain-ios-wallet#35]
User reported FaceID disables randomly upon app restarts.

for some weird reason
it keeps disabling my faceid 
it just randomly disables it and I have to turn it on in settings again 
it happened 2 times in the past 20min

when entering the app and when it asks you for face id I quit the app at the right moment and completely exited out of it (even from background processes) and when I started the app again I had to use my passcode to get into the app and turn on faceid again since it turned it off

it has all the perms in iOS Settings for app

I managed to turn the faceid off for the wallet 3 times now
without actually turning it off
idk just click on random buttons and exit and enter the app and it'll happen

iPhone 13 Pro; IOS: 15.0.2

**Comment by lastw0nd3r** [comment]
Video for this bug.

https://user-images.githubusercontent.com/10597606/142262716-25ee4a87-86ae-488d-bb08-e8651f170a00.mp4

**Comment by lastw0nd3r** [comment]
Fixed.
