### ISSUE TITLE
After deleting an APP - (without nuke)

### ISSUE THREAD

**Issue by praveshkhatana** [Meshbits/pirate-chain-ios-wallet#42]
I have deleted an APP without the 'unlinking a device' option. 
After reinstallation, It asked for an option to set a PIN and then took me to the dashboard screen directly.
It's against privacy. 
If you are pretending a user as new then he should go through all the onboarding process again and if not, you must ask for a OLD PIN (do not show an option to set new)

PS: If possible, remove all the data at the time deletion and let him recover his account from recovery key only.

@satindergrewal what's your thought on this?

**Comment by lastw0nd3r** [comment]
Closing it, as we have handled it already. Thanks
