### ISSUE TITLE
Delayed opening of Send/Receive

### ISSUE THREAD

**Issue by xKOSIUSx** [Meshbits/pirate-chain-ios-wallet#44]
As title mentions, clicking on send/receive buttons from within the wallet is noticeably delayed, closing of the said window from within the wallet is delayed as well.

Video:

https://user-images.githubusercontent.com/12998093/140484399-5c20cafb-80fb-4bbb-bfbf-e6dce3bff07b.mov

2

**Comment by lastw0nd3r** [comment]
Fixed.
