### ISSUE TITLE
Localisation of the app

### ISSUE THREAD

**Issue by satindergrewal** [Meshbits/pirate-chain-ios-wallet#9]
Need some work to be done to ensure every text in the app is localised. There shouldn't be any text which is sitting statically in the code files.

There are already localised files and holds some text variables which are being used in the app, but let's try to improve it further if we can.

Once we have the text in localised files, we'll need to make settings menu to change the language of the app without depending on system wide language settings to switch the app's language to desired language.

- [x] Make sure every static text is moved to localised files.
- [x] Make settings menu to change app language despite system wide language is different.

**Comment by lastw0nd3r** [comment]
I have kept all localisations in english, I will speak to you about the other languages.
